#url配置:
base_url:
    dev_url: http://hesh-dev.happyelements.net/hunter-dev/protocol?medhod=${method}&uid=${uid}
    Bosswang_url: http://10.130.161.81:8080/hunter-web/protocol?medhod=${method}&uid=${uid}
    design_url: http://10.130.161.81:58080/hunter-web/protocol?medhod=${method}&uid=${uid}
#当前版本号
base_version:
            version: 1.7.1

log:
    log_name: logs_
    log_level: info
    log_format: '[%(asctime)s]%(filename)s->%(funcName)s line:%(lineno)d[%(levelname)s]%(message)s'
